spring.application.name=social-api-server

jwt.secret=ThisIsMyVerySecretJwtKeyForSigningWhichIsLongEnough123!
jwt.expirationMs=300000

spring.ai.model.chat=google-genai
spring.ai.google.genai.api-key=AIzaSyBE_HMKtUwN14MRe8CYfTtuT-w5uWKjKBY

spring.datasource.url=jdbc:postgresql://localhost:5432/Social
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8082

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

