spring.application.name=social-api-server

jwt.secret=ThisIsMyVerySecretJwtKeyForSigningWhichIsLongEnough123!
jwt.expirationMs=900000

#spring.ai.model.chat=google-genai
#spring.ai.google.genai.api-key=AIzaSyAkNWUiSZ1Rzl0O3TyZLFajIPvj3ZvLvvk

# Tell Spring AI to use the OpenAI provider for chat (which we'll point to OpenRouter)
spring.ai.model.chat=openai

# OpenRouter API key (from your OpenRouter dashboard)
spring.ai.openai.api-key=dummy-key

# OpenRouter base URL (Spring will append /v1/chat/completions)
spring.ai.openai.base-url=https://openrouter.ai/api

# Choose any OpenRouter model you like, e.g. a free Llama model:
spring.ai.openai.chat.options.model=meta-llama/llama-3.3-70b-instruct:free

# Optional, but nice:
spring.ai.openai.chat.options.temperature=0.3


spring.datasource.url=jdbc:postgresql://localhost:5432/Social
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8082

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka bootstrap
spring.kafka.bootstrap-servers=localhost:9092

####################################
# Producer (JSON + String examples)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.max-request-size=10485760

logging.level.org.apache.kafka.clients.producer=DEBUG

spring.kafka.producer.properties.spring.json.add.type.headers=false


